apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webrtc-gateway.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "webrtc-gateway.name" . }}
    helm.sh/chart: {{ include "webrtc-gateway.chart" . }}
    app.kubernetes.io/instance: {{ include "webrtc-gateway.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{- $siteConfigFilePath := printf "config/pop/%s/%s.json" .Values.global.runtime.deploymentTarget "config" }}
{{- $siteConfigFile := .Files.Glob $siteConfigFilePath }}
{{- if $siteConfigFile }}
{{ $siteConfigFile.AsConfig | indent 2 }}
{{- end }}
