apiVersion: v1
kind: Service
metadata:
  name: {{ include "webrtc-gateway.name" . }}
  labels:
    {{- include "webrtc-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http }}
      protocol: TCP
      name: http
  selector:
    {{- include "webrtc-gateway.selectorLabels" . | nindent 4 }}

{{- if .Values.global.runtime.aws }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webrtc-gateway.name" . }}-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  ports:
    - port: 80
      targetPort: 9001
      protocol: TCP
  type: LoadBalancer
  selector:
    {{- include "webrtc-gateway.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webrtc-gateway.name" . }}-sip-u-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  ports:
    - port: 5060
      targetPort: 5060
      protocol: UDP
  type: LoadBalancer
  selector:
    {{- include "webrtc-gateway.selectorLabels" . | nindent 4 }}
{{- else }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webrtc-gateway.name" . }}-ws
  labels:
    {{- include "webrtc-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceWS.type }}
  ports:
    - port: {{ .Values.serviceWS.http }}
      protocol: TCP
      name: http
  selector:
    {{- include "webrtc-gateway.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webrtc-gateway.name" . }}-sip
  labels:
    app.kubernetes.io/name: {{ include "webrtc-gateway.name" . }}
    helm.sh/chart: {{ include "webrtc-gateway.chart" . }}
    app.kubernetes.io/instance: {{ include "webrtc-gateway.name" . }}
spec:
  type: NodePort
  ports:
    - name: mcu-sip
      port: 5060
      targetPort: 5060
      nodePort: 30660
      protocol: UDP
  selector:
    app.kubernetes.io/name: {{ include "webrtc-gateway.name" . }}
    app.kubernetes.io/instance: {{ include "webrtc-gateway.name" . }}
{{- end }}
